#!/usr/bin/env bash
# checking for command line argument

if [ $# -lt 4 ]
then
	echo "usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assigning paramentals to variables

path_to_file=$1
ip=$2
username="ubuntu"
key="-/.ssh/id_rsa"
path_to_ssh_key=$4

# disabbling strict host key checking

scp -o "StrictHostKeychecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"


# checking if the transfer was successful
if [ $? -eq 0 ]
then
	echo "FILE WAS TRANSFER SUCCESSFULLY"
else
	echo "FILE WAS FAILED"
fi
